# This file exists only for backwards compatibility and can be removed once all
# documentation and tools have migrated to use the new file name 'salsa-ci.yml'
include:
  - local: '/debian/salsa-ci.yml'
